SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN BOOK_SALES AS B
ON A.BOOK_ID = B.BOOK_ID
WHERE SUBSTR(B.SALES_DATE, 1, 7) = '2022-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC